/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.1.6-14-g14afc43c27-20250107"
#endif /* AVUTIL_FFVERSION_H */
